### ISSUE TITLE
RuntimeError: Unknown model (simba_l)创建模型失败

### ISSUE THREAD

**Issue by cathy345345** [raytrun/mamba-clip#4]
```
 warnings.warn(
Traceback (most recent call last):
  File "/home/hdy/heyl/code/mamba-clip-main/main.py", line 455, in <module>
    main(args)
  File "/home/hdy/heyl/code/mamba-clip-main/main.py", line 228, in main
    model = get_model(args)
            ^^^^^^^^^^^^^^^
  File "/home/hdy/heyl/code/mamba-clip-main/main.py", line 106, in get_model
    model = getattr(models, args.model)(mask_ratio=args.mask_ratio)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hdy/heyl/code/mamba-clip-main/models.py", line 273, in CLIP_Simba_L
    vision_model = create_model(
                   ^^^^^^^^^^^^^
  File "/home/hdy/anaconda3/envs/vmamba/lib/python3.11/site-packages/timm/models/factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (simba_l)
Not using distributed mode
=> creating model: CLIP_Simba_L

Process finished with exit code 1
```

创建CLIP_Simba_L模型的时候失败了，该怎么办呢？

**Comment by raytrun** [comment]
I forgot to import simba in the models file.
This issue has been addressed and is now resolved.
